version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend-network
    command: npm run dev

networks:
  backend-network:
    external: true