name: digital-store

x-common: &common
  env_file:
    - ./backend/.env

services:
  redis:
    extends:
      file: ./docker-compose.base.yml
      service: redis

  postgres:
    extends:
      file:  ./docker-compose.base.yml
      service: postgres

  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend
    <<: *common
    depends_on:
      - redis
      - postgres
    networks:
      - backend-network

  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
    depends_on:
      - backend
    networks:
      - backend-network

  webhook-simulator:
    extends: 
      file: ./scripts/docker-compose.yml
      service: webhook-simulator
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    name: digital-store_default

volumes:
  postgres_data: