services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  test-backend:
      build:
        context: .
        dockerfile: Dockerfile.test
      command: pytest
      env_file:
        - .env.test 
      depends_on:
        - redis