FROM python:3.9

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./

RUN pip install pytest pytest-asyncio httpx

COPY setup_test_db.sh ./

RUN chmod +x setup_test_db.sh

CMD ["./setup_test_db.sh"]