version: '3.8'

services:
  webhook-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - backend-network


networks:
  backend-network:
    external: true